<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="YBARTASH-NB" failures="1" tests="2" name="Error Validation Test" time="13.385" errors="0" timestamp="2023-11-15T19:03:31 EET">
  <testcase classname="udemyautomationjava.test.ErrorValidationTest" name="LoginErrorValidation" time="0.982">
=======
<testsuite ignored="0" hostname="DESKTOP-V0R7IU1" failures="1" tests="3" name="Error Validation Test" time="21.633" errors="0" timestamp="2023-11-16T12:12:03 EET">
  <testcase classname="udemyautomationjava.test.ErrorValidationTest" name="LoginErrorValidation" time="1.173">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="udemyautomationjava.test.ErrorValidationTest" name="LoginErrorValidation" time="0.56">
>>>>>>> 3a19622481c9615680e0088d97e0b8527a1f8de8
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.!] but found [Incorrect email or password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.!] but found [Incorrect email or password.]
at udemyautomationjava.test.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
<<<<<<< HEAD
  <testcase classname="udemyautomationjava.test.ErrorValidationTest" name="productErrorValidation" time="2.79"/>
=======
  <testcase classname="udemyautomationjava.test.ErrorValidationTest" name="productErrorValidation" time="2.995"/>
>>>>>>> 3a19622481c9615680e0088d97e0b8527a1f8de8
</testsuite> <!-- Error Validation Test -->
